version: "3.8"

services:
    web:
        container_name: todo_app
        build: .
        ports:
            - "8085:5000"
        volumes:
            - ./app:/app
        networks:
            - todo_lan
        depends_on:
            - mysql

    mysql:
        container_name: mysql
        platform: linux/x86_64
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: pass123
            MYSQL_DATABASE: todo_app
            MYSQL_USER: alaparic
            MYSQL_PASSWORD: pass123
        expose:
            - "3306"
        networks:
            - todo_lan
        restart: always

volumes:
    db_data:

networks:
    todo_lan:
        name: todo_lan
        driver: bridge
